name: Release Published

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publishToAlpinePackage:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.18
          check-latest: true
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Run the processing script
        env:
          ALPINE_GITLAB_ACCESS_TOKEN: ${{secrets.ALPINE_GITLAB_ACCESS_TOKEN}}
          ALPINE_GITLAB_FORK_REPO: ${{secrets.ALPINE_GITLAB_FORK_REPO}}
          GIT_USERNAME: ${{secrets.GIT_USERNAME}}
          GIT_EMAIL: ${{secrets.GIT_EMAIL}}
        working-directory: ./pipeline/alpine-publisher
        run: go run main.go
